version: "3.5"

networks:
  backend:
  frontend:

services:
  bas24apigateway:
    build:
      context: .
      dockerfile: ApiGateWay/Dockerfile
    container_name: bas24_api_gateway
    #    restart: unless-stopped
    ports:
      - "8000:80"
    networks:
      - backend
      - frontend
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
  bas24authapi:
    build:
      context: .
      dockerfile: AuthApi/Dockerfile
    container_name: bas24_auth_api
#    restart: unless-stopped
    ports:
      - "8001:80"
    networks:
      - backend