version: "3.5"

services:
  bas24-auth:
    build: .
    container_name: bas24_auth
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - bas24
#    volumes:
#      - mipd:/data

networks:
  bas24:
    name: bas24-network